# data
training_file: data/WikiSeeAlso-320K/train.txt
test_file: data/WikiSeeAlso-320K/test.txt
data_name: WikiSeeAlso-320K
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true
remove_no_label_data: true
add_special_tokens: true

# train
seed: 1337
epochs: 50
batch_size: 64
momentum: 0.9
optimizer: adam
learning_rate: ['choice', [0.0001, 0.0003, 0.001, 0.003, 0.01]]
lr_scheduler: null
scheduler_config: null
weight_decay: 0
patience: 5
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1
early_stopping_metric: P@1
val_size: 0.2

# model
model_name: XMLCNN
loss_function: binary_cross_entropy_with_logits
init_weight: kaiming_uniform
network_config:
  embed_dropout: ['choice', [0.2, 0.4, 0.6, 0.8]]
  post_encoder_dropout: ['choice', [0.2, 0.4, 0.6, 0.8]]
  filter_sizes: [8]
  hidden_dim: ['choice', [256, 512, 1024]]
  num_filter_per_size: ['choice', [96, 192, 384, 768]]
  num_pool: ['choice', [2, 8]]

# pretrained vocab / embeddings
embed_file: glove.6B.300d
vocab_file: null
normalize_embed: false

# ensemble
ensemble: false
sample_rate: 0

# hyperparameter search
search_alg: optuna
num_samples: 48
scheduler: null

# other parameters
checkpoint_path: null
cpu: false
data_workers: 4
eval: false
label_file: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
metric_threshold: 0.5
result_dir: runs
save_k_predictions: 0
silent: true
embed_cache_dir: null