# data
training_file: data/Amazon-670K/train.txt
test_file: data/Amazon-670K/test.txt
data_name: Amazon-670K
min_vocab_freq: 1
max_seq_length: 500

# train
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1
val_size: 0

# model
model_name: KimCNN
init_weight: kaiming_uniform
network_config:
  embed_dropout: 0.2
  post_encoder_dropout: 0.2
  filter_sizes: [8]
  num_filter_per_size: 384

# pretrained vocab / embeddings
embed_file: glove.6B.300d
