# data
training_file: data/Amazon-670K/train.txt
test_file: data/Amazon-670K/test.txt
data_name: Amazon-670K
min_vocab_freq: 1
max_seq_length: 512
include_test_labels: true
remove_no_label_data: true
add_special_tokens: true

# train
# seed: 777
epochs: 50
batch_size: 96
optimizer: adamw

learning_rate: 0
# learning_rate_encoder: ['grid_search', [5e-5, 7e-5]]
learning_rate_encoder: 0.00007
# learning_rate_classifier: ['grid_search', [0.005, 0.01]]
learning_rate_classifier: 0.005

momentum: 0
weight_decay: 0.001
patience: 5
early_stopping_metric: P@1
shuffle: true
val_size: 0.05
precision: 32

# scheduler - COSINE WITH WARMUP
lr_scheduler: cosine_schedule_with_warmup
scheduler_config:
  warmup_steps: 3000

# eval
eval_batch_size: 256
monitor_metrics: ['P@1', 'P@3', 'P@5']
val_metric: P@1

# model - MiniLM
model_name: SBERT
loss_function: binary_cross_entropy_with_logits
init_weight: null
network_config:
  lm_weight: sentence-transformers/all-MiniLM-L12-v2
  hidden_dropout_prob: 0.2
  attention_probs_dropout_prob: 0.1
  post_encoder_dropout: 0.2
  lm_window: 512

# pretrained vocab / embeddings
vocab_file: null
embed_file: null
normalize_embed: false

# ensemble
ensemble: false
sample_rate: 0

# hyperparameter search
search_alg: basic_variant
num_samples: 1
scheduler: null

# other parameters
checkpoint_path: null
cpu: false
data_workers: 4
eval: false
label_file: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
metric_threshold: 0.5
result_dir: runs
save_k_predictions: 0
silent: false
embed_cache_dir: null
